# Merges the .mp4 minute-by-minute video clips generated by the v3 and OG 
# WyzeCams into a single file (combined.mkv). Looks at all files in the current 
# folder. Does not re-encode the files so this should run fairly quickly.

# Reference: https://old.reddit.com/r/wyzecam/comments/skcjzr/software_to_stitch_video_together/hvkzwnh/ 
# Archive link: https://web.archive.org/web/20220204170600/https://old.reddit.com/r/wyzecam/comments/skcjzr/software_to_stitch_video_together/hvkzwnh/

for f in *.mp4 ; do echo file \'$f\' >> list.txt; done && ffmpeg -safe 0 -f concat -i list.txt -c copy combined.mkv -an